### ISSUE TITLE
Blacklist of orgs/repos

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-backend#78]
We need to support a blacklist in order to remove contents from the catalog.

**Comment by libremente** [comment]
Yes, I believe this is an important feature. 
Proceding in steps, I think that starting by blacklisting single repos would be nice. Then it could be nice to add also orgs.

**Comment by libremente** [comment]
This is priority right now.
The `blacklist.yml` file must contain a list of repositories to be `temporarily` removed from the Developers Italia catalog because of an infringment in the following [rules](https://docs.italia.it/italia/developers-italia/policy-inserimento-catalogo-docs/it/stabile/index.html). Also, it has to contain the reason for this temporary removal and its description. 
This is the format:
```
# Policy https://docs.italia.it/italia/developers-italia/policy-inserimento-catalogo-docs/it/stabile/approvazione-del-software-a-catalogo.html
repos:
  - url: https://github.com/italia/repo1
    reason: 1
    description: GitHub takedown
```

The design should be the following:
* create a `blacklist.yml` file to be stored inside the repository;
* when reading the URL list, check whether the URL is blacklisted;
* if yes, print and error in the log and continue with the following URL.

cc @sebbalex
